apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-top
  name: app-top
spec:
  type: LoadBalancer
  selector:
    role: app-top
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
